SELECT * FROM online_sales_data.`online sales data`;

Create table onlinesales
like online_sales_data.`online sales data`;

insert into onlinesales
SELECT * FROM online_sales_data.`online sales data`;

select *
from onlinesales;

SELECT `Date`, COUNT(*)
FROM onlinesales
GROUP BY `Date`
HAVING COUNT(*) > 1;

DELETE t1
FROM onlinesales t1
JOIN onlinesales t2 ON t1.Date = t2.Date;

Alter table onlinesales
rename column `Transaction ID` to TransactionID;

Alter table onlinesales
rename column `Date` to PurchaseDate;

Alter table onlinesales
rename column `Product Category` to ProductCategory;

Alter table onlinesales
rename column `Product Name` to ProductName;

Alter table onlinesales
rename column `Units Sold` to UnitsSold;

Alter table onlinesales
rename column `Unit Price` to UnitPrice;

Alter table onlinesales
rename column `Total Revenue` to TotalRevenue;

Alter table onlinesales
rename column `Payment Method` to PaymentMethod;

-- The payment method used in Europe is Paypal
SELECT *
FROM onlinesales
WHERE Region = 'Europe';

-- total revenue by each product category. Electronics have the most revenue followed by home appliances. the lowest revenue is from books.
SELECT ProductCategory, SUM(TotalRevenue) AS Total_Revenue
FROM onlinesales
GROUP BY ProductCategory
order by Total_Revenue desc;

-- top 5 best selling products based on total products sold. Hanes ComfortSoft Tshirt is the best selling.
SELECT ProductName, SUM(UnitsSold) AS Total_Units_Sold
FROM onlinesales
GROUP BY ProductName
ORDER BY Total_Units_Sold DESC
LIMIT 5;

-- average unit price of products sold in Asia
SELECT AVG(UnitPrice) AS Average_Unit_Price
FROM onlinesales
WHERE Region = 'Asia';

-- transactions where the payment method is paypal and the total revenue is above 500
-- all the producta are home appliances with LG OLED TV having the highest revenue
SELECT *
FROM onlinesales
WHERE PaymentMethod = 'PayPal' AND TotalRevenue > 500
order by TotalRevenue desc;

-- The month with the highest total revenue is month 4 (April)
SELECT MONTH(PurchaseDate) AS Month, SUM(TotalRevenue) AS Total_Revenue
FROM onlinesales
GROUP BY MONTH(PurchaseDate), TotalRevenue
ORDER BY TotalRevenue DESC
LIMIT 1;

-- Total Revenue for each month
SELECT MONTH(PurchaseDate) AS Month, SUM(TotalRevenue) AS Total_Revenue
FROM onlinesales
WHERE YEAR(PurchaseDate) = 2024
GROUP BY MONTH(PurchaseDate)
ORDER BY Month;

-- Top 3 Payment methods used
SELECT PaymentMethod, COUNT(*) AS Transaction_Count
FROM onlinesales
GROUP BY PaymentMethod
ORDER BY Transaction_Count DESC
LIMIT 3;

-- the average total revenue is around 335
SELECT AVG(TotalRevenue) AS Average_Total_Revenue
FROM onlinesales;

-- Top 5 customers with the highest total spending
SELECT TransactionID, SUM(TotalRevenue) AS Total_Spending
FROM onlinesales
GROUP BY TransactionID
ORDER BY Total_Spending DESC
LIMIT 5;

-- Total revemue for each region. North America leads then Asia and Europe
SELECT Region, SUM(TotalRevenue) AS Total_Revenue
FROM onlinesales
WHERE YEAR(PurchaseDate) = 2024
GROUP BY Region
order by Total_Revenue desc;

-- average units sold is around 2 units
SELECT AVG(UnitsSold) AS Average_Units_Sold
FROM onlinesales;

-- electronics paid for using a credit card. All are from North America
SELECT *
FROM onlinesales
WHERE ProductCategory = 'Electronics' AND PaymentMethod = 'Credit Card';

-- North America preferred payment method is credit cards
SELECT *
FROM onlinesales
WHERE Region = 'North America';

-- revenue generated by each product in the electronics category. The Canon EOS R5 camera has the highest revenue
SELECT ProductName, SUM(TotalRevenue) AS Total_Revenue
FROM onlinesales
WHERE ProductCategory = 'Electronics'
GROUP BY ProductName
order by Total_Revenue desc;

-- Month 1 has the highest average total revenue
SELECT MONTH(PurchaseDate) AS Month, AVG(TotalRevenue) AS Avg_Total_Revenue
FROM onlinesales
GROUP BY MONTH(PurchaseDate)
ORDER BY Avg_Total_Revenue DESC
LIMIT 1;

-- Customers who madde more than 1 purchase. No customer made more than 1 purchase
SELECT TransactionID, COUNT(DISTINCT PurchaseDate) AS Purchase_Dates
FROM onlinesales
GROUP BY TransactionID
HAVING Purchase_Dates > 1;

--  the total revenue for each product sold in 2024, ordered by total revenue in descending order
SELECT ProductName, SUM(TotalRevenue) AS Total_Revenue
FROM onlinesales
WHERE YEAR(PurchaseDate) = 2024
GROUP BY ProductName
ORDER BY Total_Revenue DESC;

-- the average unit price for each product category
SELECT ProductCategory, AVG(UnitPrice) AS Avg_Unit_Price
FROM onlinesales
GROUP BY ProductCategory
order by Avg_Unit_Price desc;

-- the customers who made the highest single transaction (by total revenue). Customer 10103 made a transaction of 3899.99
SELECT TransactionID, MAX(TotalRevenue) AS Max_Total_Revenue
FROM onlinesales
GROUP BY TransactionID
ORDER BY Max_Total_Revenue DESC
LIMIT 1;

-- the total revenue for each customer in 2024, sorted by total revenue (descending)
SELECT TransactionID, SUM(TotalRevenue) AS Total_Revenue
FROM onlinesales
WHERE YEAR(PurchaseDate) = 2024
GROUP BY TransactionID
ORDER BY Total_Revenue DESC;

-- the average transaction value for each payment method
SELECT PaymentMethod, AVG(TotalRevenue) AS Avg_Transaction_Value
FROM onlinesales
GROUP BY PaymentMethod;

SELECT Region, SUM(TotalRevenue) AS Total_Revenue
FROM onlinesales
WHERE YEAR(PurchaseDate) = 2024
GROUP BY Region
ORDER BY Total_Revenue DESC
LIMIT 5;

SELECT DAYNAME(PurchaseDate) AS Day_of_Week, SUM(TotalRevenue) AS Total_Revenue
FROM onlinesales
GROUP BY Day_of_Week
ORDER BY FIELD(Day_of_Week, 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday');

-- Average units sold per category
SELECT ProductCategory, AVG(UnitsSold) AS Avg_Units_Sold
FROM onlinesales
GROUP BY ProductCategory;

-- the total revenue for each month of 2024, ordered by total revenue (descending)
SELECT YEAR(PurchaseDate) AS Year, MONTH(PurchaseDate) AS Month, SUM(TotalRevenue) AS Total_Revenue
FROM onlinesales
WHERE YEAR(PurchaseDate) = 2024
GROUP BY Year, Month
ORDER BY Total_Revenue DESC;

-- the total revenue for each day in 2024, sorted by date
SELECT PurchaseDate, SUM(TotalRevenue) AS Total_Revenue
FROM onlinesales
WHERE YEAR(PurchaseDate) = 2024
GROUP BY PurchaseDate
ORDER BY PurchaseDate;

SELECT ProductName, SUM(TotalRevenue) AS Total_Revenue
FROM onlinesales
WHERE YEAR(PurchaseDate) = 2024
GROUP BY ProductName
HAVING Total_Revenue > 1000
ORDER BY Total_Revenue DESC;




























